### ISSUE TITLE
Unable to get the word 'Swatantrata' in Hindi; thr missing

### ISSUE THREAD

**Issue by YaminiVijayan** [varnamproject/libvarnam#131]
Oddly, able to get the word in the inside pages, screenshot attached
![img_20150827_163800](https://cloud.githubusercontent.com/assets/11420496/9519262/ce05d458-4cda-11e5-9c91-773e823e0cb7.jpg)

But unable to get it for the Title of the book. Or even on Github. It becomes: स्वतंत्रता

Also, for the word yatra, which become यात्रा.

**Comment by YaminiVijayan** [comment]
Link of story here: https://storyweaver.org.in/stories/804-swatantrata-ki-ore

**Comment by jijeshmohan** [comment]
This is showing properly in my system 

<img width="699" alt="screen shot 2015-09-11 at 9 55 30 am" src="https://cloud.githubusercontent.com/assets/43115/9807077/7967cb58-586b-11e5-855d-614050c1beda.png">

This might be the problem with the font you are using in your machine ( inside pages it is using google fonts instead of system font ) .
